### ISSUE TITLE
Integration throws multiple errors

### ISSUE THREAD

**Issue by financelurker** [ItsEcholot/ha-paperless-ng-sensor#1]
Hi!

After configuring the integration in my HA instance I see the following errors in my log:
```
2022-09-25 08:25:08.860 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing paperless_ng/group.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.paperless-ng.group'
2022-09-25 08:25:08.931 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing paperless_ng/diagnostics.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.paperless-ng.diagnostics'
2022-09-25 08:25:08.934 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing paperless_ng/recorder.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.paperless-ng.recorder'
2022-09-25 08:25:08.936 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing paperless_ng/media_source.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.paperless-ng.media_source'
2022-09-25 08:25:08.939 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing paperless_ng/logbook.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.paperless-ng.logbook'
2022-09-25 08:25:08.942 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing paperless_ng/system_health.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.paperless-ng.system_health'
2022-09-25 08:25:12.913 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing paperless_ng/hardware.py
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
platform = integration.get_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 681, in get_platform
cache[full_name] = self._import_platform(platform_name)
File "/usr/src/homeassistant/homeassistant/loader.py", line 698, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.paperless-ng.hardware'
```

HA-Info:
- Home Assistant 2022.9.6
- Supervisor 2022.09.1
- Frontend 20220907.2 - latest

**Comment by ItsEcholot** [comment]
Thanks for the report!
I have stopped using the integration myself and thus didn't realize it wasn't working.
I will try to take some time this weekend to rewrite & fix this.

**Comment by Ionshard** [comment]
I was able to install this just now and I don't seem to have those errors. I just added this repo as a custom repository to HACS and then configured it on the UI. Everything seems to be working for me.

**Comment by Ionshard** [comment]
@financelurker How did you install this integration? Looking at the logs something seems off, it looks like HA is trying to load a lot of things that are not defined in the repo. For example `Unexpected error importing paperless_ng/diagnostics.py` but there is no `diagnostics.py` and no where in the source code here does it try to import `diagnostics.py` so might be a misconfiguration on HA's side.

**Comment by financelurker** [comment]
huh... I think this issue can be closed (if it's not reproducible). I have moved on and have removed that sensor from my HA installation :)

**Comment by ItsEcholot** [comment]
> @financelurker How did you install this integration? Looking at the logs something seems off, it looks like HA is trying to load a lot of things that are not defined in the repo. For example `Unexpected error importing paperless_ng/diagnostics.py` but there is no `diagnostics.py` and no where in the source code here does it try to import `diagnostics.py` so might be a misconfiguration on HA's side.

I had this at some point during development as well... It's to long ago so I don't remember what was up with that. But if it still seems to be working for @Ionshard on the latest HA version I will close this for now.
